name: Publish Release to GitHub

on:
  push:
    if: github.ref_name == 'main'
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish release
        uses: ghalactic/github-release-from-tag@v5
        with:
          generateReleaseNotes: 'true'
          prerelease: 'false'
          summaryEnabled: 'false'
